SlamTalk/slam-talk-backend

src/main/java/sync/slamtalk/common/ApiResponse.java, src/main/java/sync/slamtalk/common/BaseException.java, src/main/java/sync/slamtalk/common/ErrorResponseCode.java, src/main/java/sync/slamtalk/common/ResponseCodeDetails.java
-  ResponseCodeDetails 라는 Interface 생성
-  GlobalRestControllerAdivice 및 BaseExcextion, ApiResponse 에서 인터페이스를 반환하고 객체로 사용하도록 수정
- ResponseInterface를 상속받으면 기능별로 커스텀하게 에러를 만들 수 있습니다.(ErrorResponseCode 참고)
resolved: #28
=> #28 refactor: ErrorResponseCode

src/main/java/sync/slamtalk/map/controller/BasketballCourtController.java, src/main/java/sync/slamtalk/map/dto/BasketballCourtDto.java, src/main/java/sync/slamtalk/map/dto/BasketballCourtErrorResponse.java, src/main/java/sync/slamtalk/map/entity/AdminStatus.java, src/main/java/sync/slamtalk/map/entity/BasketballCourt.java, src/main/java/sync/slamtalk/map/mapper/BasketballCourtMapper.java, src/main/java/sync/slamtalk/map/repository/BasketballCourtRepository.java, src/main/java/sync/slamtalk/map/service/BasketballCourtService.java
-   #13 
- 농구장 entity & dto 생성, 변환 구현
- 마커 띄울 농구장 간략 정보(id,이름,위도,경도) 전달
- 특정 농구장 전체 정보 전달
close #13
=> #13 근처 농구장 마커 표시 & 클릭시 해당 시설 정보 표시

build.gradle, src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java, src/main/java/sync/slamtalk/chat/config/CustomWebSocketHandler.java, src/main/java/sync/slamtalk/chat/config/StompErrorHandler.java, src/main/java/sync/slamtalk/chat/config/StompWebSocketConfig.java, src/main/java/sync/slamtalk/chat/controller/ChatController.java, src/main/java/sync/slamtalk/chat/controller/StompChatController.java, src/main/java/sync/slamtalk/chat/dto/ChatErrorResponseCode.java, src/main/java/sync/slamtalk/chat/dto/Request/ChatCreateDTO.java, src/main/java/sync/slamtalk/chat/dto/Request/ChatMessageDTO.java, src/main/java/sync/slamtalk/chat/dto/Response/ChatRoomDTO.java, src/main/java/sync/slamtalk/chat/entity/Messages.java, src/main/java/sync/slamtalk/chat/entity/UserChatRoom.java, src/main/java/sync/slamtalk/chat/entity/UserMock.java, src/main/java/sync/slamtalk/chat/repository/ChatRoomRepository.java, src/main/java/sync/slamtalk/chat/repository/MessagesRepository.java, src/main/java/sync/slamtalk/chat/repository/UserMockRepository.java, src/main/java/sync/slamtalk/chat/service/ChatService.java, src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java, src/test/java/sync/slamtalk/chat/repository/ChatRoomRepositoryTest.java, src/test/java/sync/slamtalk/chat/repository/MessagesRepositoryTest.java
- 채팅방 id를 통해 다시 채팅방에 접속하는 로직 추가 -> STOMP 메세지를 보내면 되는거였음, 대신 입장 시 사용될 채팅방 컨트롤러 추가함(아래내용에포함)
- 채팅방 생성, 유저의 채팅리스트 조회, 채팅방 과거 내역 조회 컨트롤러 수정 및 추가
- 채팅방 유효성 확인(존재여부,사용자가참여한채팅방여부) 서비스 추가
- 채팅방 채팅 내역 조회, 채팅리스트 내역 조회 서비스 추가
- 채팅방 뒤로 가기 시 마지막 메세지 아이디 저장
- STOMP MESSAGE FRAME DISCONNECT 로직 추가(POSTMAN)
- 👀 참고해주세요
- ‼️ 📢 userMock 은 이번 pr merge 후에 완전히 삭제할 예정입니다(user_mock -> user Entity 로 변경)
- ‼️ 📢 test 코드 추가로 build.gradle 수정 사항이 발생했습니다.
- ‼️ 📢 기능 방향에 대해 논의중인것들이 있어서 TODO(아직 미완성 혹은 작성안함) 와 주석 등 코드가 지저분 합니다. 
이부분은 추후 리팩토링 할 예정입니다.
resolved #44
=> #44 채팅리스트 요구사항 서비스,컨트롤러 작성 외

src/main/java/sync/slamtalk/mate/controller/MatePostController.java, src/main/java/sync/slamtalk/mate/controller/ParticipantController.java, src/main/java/sync/slamtalk/mate/dto/MateFormDTO.java, src/main/java/sync/slamtalk/mate/dto/MatePostApplicantDTO.java, src/main/java/sync/slamtalk/mate/entity/MatePost.java, src/main/java/sync/slamtalk/mate/entity/Participant.java, src/main/java/sync/slamtalk/mate/entity/PositionType.java, src/main/java/sync/slamtalk/mate/entity/RecruitedSkillLevelType.java, src/main/java/sync/slamtalk/mate/entity/SkillLevelType.java, src/main/java/sync/slamtalk/mate/error/MateErrorResponseCode.java, src/main/java/sync/slamtalk/mate/error/UserErrorResponseCode.java, src/main/java/sync/slamtalk/mate/service/MatePostService.java, src/main/java/sync/slamtalk/mate/service/ParticipantService.java
> 이번 PR에서 작업한 내용을 간략히 설명해주세요.
-  신청자 목록 관련 기능 개발 (#47 이슈 참조)
-  메이트 찾기 및 신청자 목록 컨트롤러와 서비스 파일 분리.
-  엔터티 별 hashCode()와 equals(), 순환참조를 고려한 toString() 메서드 오버라이딩 함.
-  연관관계 편의 메서드 도입
-  프론트엔드와 조율하여 기능 수정
-  현재로써 일어날 법한 기본적인 예외 처리
-  ENUM 타입 통일을 위한 수정 및 추가
-  service계층의 메서드 별 여러가지 케이스를 고려한 테스트 진행 -> 통과
-  (*이슈 해결) 회원가입 API 요청이 실패로 돌아오는 이슈 해결!
-  api 요청 테스트 시 발생 이슈 해결! (#59 이슈 참조)
> 앞으로 진행할 예정인 이슈
- 프론트엔드로 반환하기 위한 SkillTypeList로 변환 메서드 생성
- 프론트엔드와 추가 논의 후 수정 작업 예정
- 다음 개발 단계 진행(메이트 찾기 글 목록)
closed #47 
closed #59
=> #47 메이트 찾기,신청자 목록 관련 리팩토링 및 기능 추가

src/main/java/sync/slamtalk/SlamtalkApplication.java, src/main/java/sync/slamtalk/security/config/CorsConfig.java, src/main/java/sync/slamtalk/security/config/SecurityConfig.java, src/main/java/sync/slamtalk/security/dto/JwtTokenDto.java, src/main/java/sync/slamtalk/security/jwt/JwtTokenProvider.java, src/main/java/sync/slamtalk/security/logout/CustomLogoutHandler.java, src/main/java/sync/slamtalk/security/oauth2/CustomOAuth2User.java, src/main/java/sync/slamtalk/security/oauth2/OAuthAttributes.java, src/main/java/sync/slamtalk/security/oauth2/handler/OAuth2LoginFailureHandler.java, src/main/java/sync/slamtalk/security/oauth2/handler/OAuth2LoginSuccessHandler.java, src/main/java/sync/slamtalk/security/oauth2/service/CustomOAuth2UserService.java, src/main/java/sync/slamtalk/security/oauth2/userinfo/GoogleOAuth2UserInfo.java, src/main/java/sync/slamtalk/security/oauth2/userinfo/KakaoOAuth2UserInfo.java, src/main/java/sync/slamtalk/security/oauth2/userinfo/NaverOAuth2UserInfo.java, src/main/java/sync/slamtalk/security/oauth2/userinfo/OAuth2UserInfo.java, src/main/java/sync/slamtalk/security/utils/CookieUtil.java, src/main/java/sync/slamtalk/swagger/test/Controller.java, src/main/java/sync/slamtalk/user/UserController.java, src/main/java/sync/slamtalk/user/UserRepository.java, src/main/java/sync/slamtalk/user/UserService.java, src/main/java/sync/slamtalk/user/dto/UserLoginRequestDto.java, src/main/java/sync/slamtalk/user/dto/UserLoginResponseDto.java, src/main/java/sync/slamtalk/user/dto/UserSignUpRequestDto.java, src/main/java/sync/slamtalk/user/entity/User.java, src/test/java/sync/slamtalk/user/UserServiceTest.java
- 소셜 로그인 구현하기
- 로그인 시 헤더에 Authroization 토큰 반환 및, 바디에 정보수집여부 반환
- OAuth 2.0 로직 추가
- 시큐리티 logout api 설정 추가
- 회원가입 시 로그인 까지 해주는 로직 추가
- 토큰 재발급 시에 쿠키에 있는 refreshToken을 이용해서 만료검사 및 엑세스토큰 리프레시 토큰 재발급 로직 리팩터링
- 통합 테스트 를 위해 총미님께 다음 내용을 공유할 예정입니다.
resolved : #6 
resolved : #56
=> #6 #56 Feature 소셜 로그인 기능 추가 및 토큰 저장 방식 리팩터링

src/main/java/sync/slamtalk/security/oauth2/handler/OAuth2LoginSuccessHandler.java
- 변경점 : http://localhost:3000 로 변경되었습니다
- 이유 : 테스트 환경이라 localhost로 해두고 배포환경에서는 front측의 url로 수정할 계획입니다.
=> #92 refactor  카카오 로그인 성공시 응답 url 수정

src/main/java/sync/slamtalk/user/controller/AuthController.java, src/main/java/sync/slamtalk/user/controller/UserController.java, src/main/java/sync/slamtalk/user/dto/UserDetailsInfoResponseDto.java, src/main/java/sync/slamtalk/user/error/UserErrorResponseCode.java, src/main/java/sync/slamtalk/user/service/AuthService.java, src/main/java/sync/slamtalk/user/service/UserService.java, src/test/java/sync/slamtalk/user/AuthServiceTest.java
- 유저 마이페이지에 들어갈 api 개발을 하였습니다
- 기존 로그인/회원가입/리프레쉬 토큰을 담당하던 UserService -> AuthService, UserController -> AuthController로 이름 변경 했습니다
- 프로필에서 닉네임, 이메일, 한마디, 포지션, 농구 실력, 활동 내역(레벨)를 표시한다.
- 미완성 : 팀 매칭 횟수, 농구 메이트 참여 횟수
- 사유 : 팀 매칭 테이블 미완 및 농구 Repo 동수님이 개발중이신 부분이 있어서 그것 다음부터 개발할 예정입니다!
=> #80 유저 마이페이지 기능 구현(미완성)

src/main/java/sync/slamtalk/security/config/SecurityConfig.java
- 앞선 성환님이 작성하신 "/api/map/courts/**" 로 설정해두어서 해당 /api/map/courts 를 포함한 아래의 모든 하위 경로의 GET 매서드로의 요청을 permitAll(전체허용)하는 설정을 추가하였습니다.
=> #89 #100 시큐리티필터링에 게스트 해당 url 추가하는 설정 

src/main/java/sync/slamtalk/common/BaseEntity.java, src/main/java/sync/slamtalk/mate/controller/ParticipantController.java, src/main/java/sync/slamtalk/mate/entity/ApplyStatusType.java, src/main/java/sync/slamtalk/mate/entity/MatePost.java, src/main/java/sync/slamtalk/mate/entity/RecruitmentStatusType.java, src/main/java/sync/slamtalk/mate/service/MatePostService.java, src/main/java/sync/slamtalk/mate/service/ParticipantService.java, src/main/java/sync/slamtalk/team/controller/TeamMatchingController.java, src/main/java/sync/slamtalk/team/dto/ToApplicantDto.java, src/main/java/sync/slamtalk/team/dto/ToTeamFormDTO.java, src/main/java/sync/slamtalk/team/dto/ToTeamMatchingListDto.java, src/main/java/sync/slamtalk/team/entity/TeamApplicant.java, src/main/java/sync/slamtalk/team/entity/TeamApplyStatusType.java, src/main/java/sync/slamtalk/team/entity/TeamMatching.java, src/main/java/sync/slamtalk/team/error/TeamErrorResponseCode.java, src/main/java/sync/slamtalk/team/repository/TeamApplicantRepository.java, src/main/java/sync/slamtalk/team/repository/TeamMatchingRepository.java, src/main/java/sync/slamtalk/team/service/TeamMatchingService.java
-  CANCEL -> CANCELED로 수정함.
-  팀 신청자 엔티티 생성
-  팀매칭 목록 조회 기능 및 해당 팀매칭 게시글에 신청하기 기능 구현
-  dto 관련 리팩토링 진행
-  엔티티 클래스명 수정(TeamMatchings -> TeamMatching)
-  해당 기능 api 기본적인 요청 테스트 완료
closed #95
=> #95 팀매칭 신청자 엔티티, 계층구조 생성 및 팀매칭 목록 구현

src/main/java/sync/slamtalk/common/GlobalRestControllerAdvice.java, src/main/java/sync/slamtalk/mate/repository/MatePostRepository.java, src/main/java/sync/slamtalk/security/oauth2/OAuthAttributes.java, src/main/java/sync/slamtalk/user/dto/UserDetailsInfoResponseDto.java, src/main/java/sync/slamtalk/user/dto/UserSignUpRequestDto.java, src/main/java/sync/slamtalk/user/entity/User.java, src/main/java/sync/slamtalk/user/service/UserService.java, src/test/java/sync/slamtalk/mate/repository/MatePostRepositoryTest.java
- controller에서 dto로 enum을 받고 있을때 enum 에 존재하지 않는 문자열을 받을 때 서버가 던지는 HttpMessageNotReadableException 을 400에러로 커스텀
- GlobalRestControllerAdvice.java 추가 
- User 엔티티 수정
- MatePostRepository 코드 추가 되었습니다
- feat/99-info 충돌해결하고 pr 날리기
resolved : #80
=> #80 유저 마이페이지  사용자의 level 및 팀 매칭 완료 횟수를 보여주는 로직 추가

src/main/java/sync/slamtalk/security/oauth2/OAuthAttributes.java, src/main/java/sync/slamtalk/security/oauth2/service/CustomOAuth2UserService.java, src/main/java/sync/slamtalk/security/oauth2/userinfo/GoogleOAuth2UserInfo.java, src/main/java/sync/slamtalk/security/oauth2/userinfo/NaverOAuth2UserInfo.java
- 구글 OAuth 2.0 을 통해서 소셜 로그인 구현하기
- 네이버 OAuth 2.0 을 통해서 소셜 로그인 구현하기
- application-oauth.yml 파일이 수정되었습니다!
=> #110 feat : Naver, Google 소셜 로그인 구현

src/main/java/sync/slamtalk/user/controller/AuthController.java, src/main/java/sync/slamtalk/user/dto/UserDetailsAfterRefreshResponseDto.java, src/main/java/sync/slamtalk/user/dto/UserDetailsInfoResponseDto.java, src/main/java/sync/slamtalk/user/dto/UserSignUpRequestDto.java, src/main/java/sync/slamtalk/user/entity/User.java, src/main/java/sync/slamtalk/user/error/UserErrorResponseCode.java, src/main/java/sync/slamtalk/user/service/AuthService.java, src/main/java/sync/slamtalk/user/service/UserService.java, src/test/java/sync/slamtalk/user/AuthServiceTest.java
- 리프레쉬 토큰 인증관련 에러를 401로 변경
- 리프레쉬 요청 시 마이 페이지에 필드를 모두 다 추가하기!
- email
- socialType
- selfIntroduction
- basketballSkillLevel
- basketballPosition
- level
- levelScore
- mateCompleteParticipationCount
- teamMatchingCompleteParticipationCount
=> #113 feat : 113 refresh token add field

src/main/java/sync/slamtalk/common/ErrorResponseCode.java, src/main/java/sync/slamtalk/common/s3bucket/FileUploadController.java, src/main/java/sync/slamtalk/common/s3bucket/repository/AwsS3RepositoryImpl.java
> s3bucket 에서 객체 key를 전체 url로  잘못설정해서 제대로 삭제가 안되고있었습니다. 파일을 삭제할 때는 객체 '키'를 이용해서 삭제해야 합니다. 
> 예외처리 수정이 필요합니다 🥲 수정 완료하면 말씀드릴게요! 그때 리뷰해주시면 좋을 거 같습니다. 이점 양해부탁드립니다!
closed #88 #91
=> #88,91 s3bucket 이미지 업로드 검증메서드 추가, 이미지 삭제수정

src/main/java/sync/slamtalk/common/GlobalRestControllerAdvice.java, src/main/java/sync/slamtalk/security/jwt/JwtTokenProvider.java, src/main/java/sync/slamtalk/user/controller/AuthController.java, src/main/java/sync/slamtalk/user/controller/UserController.java, src/main/java/sync/slamtalk/user/dto/UserDetailsMyInfoResponseDto.java, src/main/java/sync/slamtalk/user/dto/UserDetailsOtherInfoResponseDto.java, src/main/java/sync/slamtalk/user/service/AuthService.java, src/main/java/sync/slamtalk/user/service/UserService.java, src/test/java/sync/slamtalk/user/AuthServiceTest.java, src/test/java/sync/slamtalk/user/service/UserServiceTest.java
- jwtProvider 설정 변경
- 기존 RTR 방식 (액세스 토큰 재발급 시 리프레시 토큰도 재발급) 에서 리프레시 토큰은 7일 동안만 유효하도록 설정을 변경
- /api/user/my-info 요청시 나의 user 정보를 반환하기
- /api/user/{userId}/other-info 요청 시 상대방의 user 정보 반환하기(email, socialType 제외)
- /api/token/accessToken 요청 시 엑세스 토큰 반환하기, 반환 해주는 body에 user정보 제외하기
- /api/tokens/refresh 요청 시 엑세스 토큰 반환하기, 반환 해주는 body에 user정보 제외하기
- 무조건 엑세스 토큰을 재발급 한다.
- 리프래쉬 토큰이 만료가 되었다면 재로그인을 한다!
resolved: #141
=> #141 유저 관련 리프레시 재발급 로직 수정 및 반환 타입 수정

src/main/java/sync/slamtalk/security/oauth2/handler/OAuth2LoginSuccessHandler.java
- 기존 : localhost:3000 테스트 용 서버로 전송
- 변경 : localhost:3000/social-login 으로 전송 하기!
- 변경 사유 : 프론트 측에서 accessToken 재발급 요청을 보내기 위해서 다음과 같이 url을 변경하였습니다!
- 소셜 로그인 시에 서버 측에서 리다이렉트를 시켜버리면 쿠키와 파라미터 밖에 전달 되지않아서 이렇게 수정하게되었습니다!
=> #141 refactor : 소셜로그인 완료 시 리다이렉트 url 변경

src/main/java/sync/slamtalk/chat/service/ChatService.java, src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java, src/main/java/sync/slamtalk/user/entity/User.java, src/test/java/sync/slamtalk/chat/service/ChatServiceImplTest.java
- 팀매칭 / 상대팀 매칭 완료 시 채팅방 생성 후 해당 채팅방 id에 해당하는UserChatRoom에 User 리스트 추가하는 메서드
- 구현 이유 : 매칭 완료 시 참여한 모든 유저가 채팅 리스트에서 해당 채팅이 보여야하기 때문에 구현하였습니다.
- ChatServiceImplTest.java 를 통해서 테스트를 수행하였습니다!
- 정상적으로 db에 저장되는 로직을 확인하였습니다
resolved : #144
=> #144 feat : setUserListChatRoom 메서드 구현

src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java, src/main/java/sync/slamtalk/chat/dto/Request/ChatCreateDTO.java, src/main/java/sync/slamtalk/chat/dto/Request/ChatMessageDTO.java, src/main/java/sync/slamtalk/chat/dto/Response/ChatRoomDTO.java, src/main/java/sync/slamtalk/chat/entity/ChatRoom.java, src/main/java/sync/slamtalk/chat/entity/Messages.java, src/main/java/sync/slamtalk/chat/entity/UserChatRoom.java, src/main/java/sync/slamtalk/chat/repository/UserChatRoomRepository.java, src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
- 채팅내역에 응답에 senderId, imgUrl 추가
- 채팅리스트에서 농구장 에서 형성된 채팅방이면 프로필을 눌렀을 때 농구장 정보로 이동할 수 있도록 id 추가,
1:1 인 경우에는 상대방 프로필 눌렀을 때 상대방 마이페이지에 대한 정보를 주기 위해 userId 추가
- 채팅리스트 응답에 roomType 추가
- roomtype @Enumerated 어노테이션 추가하여 ENUM 클래스 값으로 테이블 값 표시
- chatcreate (채팅방생성요청) 요청 api 수정
- 👀 같이 리뷰 필요
- Message entity 스키마 변경하여서 db 초기화하고 다시 생성해야할거 같은데 혹시 수작업으로 넣으신 데이터가 많을까요?ㅠㅠ
db초기화 안하고 실행시키면 아마 에러가 날거같은데 이 부분은 이야기 나누어봐야할거같습니다..🥲
=> #137 chat API 수정

src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java, src/main/java/sync/slamtalk/chat/controller/ChatController.java, src/main/java/sync/slamtalk/chat/controller/StompChatController.java, src/main/java/sync/slamtalk/chat/dto/ChatErrorResponseCode.java, src/main/java/sync/slamtalk/chat/dto/Request/ChatMessageDTO.java, src/main/java/sync/slamtalk/chat/dto/Response/ChatRoomDTO.java, src/main/java/sync/slamtalk/chat/entity/ChatRoom.java, src/main/java/sync/slamtalk/chat/entity/UserChatRoom.java, src/main/java/sync/slamtalk/chat/repository/UserChatRoomRepository.java, src/main/java/sync/slamtalk/chat/service/ChatService.java, src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
✅ **userchatroom 생성 시기 변경**
- 기존 : subscribe 이후에 생성
- 현재 : 농구장채팅방을 제외하고, 채팅방생성시점에 생성
[ 1:1채팅방, 같이해요채팅방, 팀매칭채팅방 ]
> 채팅방 **생성시점**에 userchatroom 에 추가하여 채팅방 생성자 및 참여자들의 chatlist 에서 채팅방 확인이 가능
[ 농구장채팅방 ]
> "농구장코드정보 : 채팅방" 이므로 유저가 채팅방 **접속시점**에 userchatroom 에 추가하여 참여자들의 chatlist 에서 채팅방 확인이 가능
✅ **채팅방 중복 생성 방지**
- 기존 : 채팅방 생성 시 동일한 상대와 채팅방에도 불구하고 새로운 채팅방이 계속 생성됨
- 현재 : 채팅방 생성 시 참여자(채팅방 생성자 포함) 모두 생성 요청에 있는 roomType, roomname 으로 userchatroom 에 가지고 있는 지 확인 후 한명이라도 userchatroom 에 존재하지 않으면 새롭게 생성, 모두 동일한 채팅방을 userchatroom 에 가지고 있다면 기존 채팅방 id 반환
✅ **채팅방 첫접속/재접속 검증**
- 기존 :  ChatIboundInterceptor 에서 메서드 작성 및 호출
- 현재 :  ChatService 에 검증메서드 추가, STOMP Message Controller 에서 호출
[ SEND_ENTER 메세지 프레임 형식 ]
> roomId, senderId, senderNickname
✅ **농구장과 연관관계 매핑 주석 제거**
- 📢 테이블 필드 추가 및 연관관계 매핑 코드 추가로 인해 서버 DB 초기화가 …
=> #158,#166 채팅방 입장 전 로직 유형별 수정, 중복생성과 접속 유형 검증 메서드 추가

src/main/java/sync/slamtalk/security/config/SecurityConfig.java
- 아래의 url들을 Spring Security 에서 Authentication 검증을 안하도록 설정하였습니다.
- jwtFilter에서 위의 url들을 안거치도록 yml 파일을 다음과 같이 수정했습니다.
```
. . .
/api/mate/read,
/api/mate/list,
/api/match/read,
/api/match/list
```
- application.yml 파일에 위의 exclude path가 추가되었습니다.
resolved : #174
=> #174 feat : 팀매칭/상대팀 매칭 게스트 api 추가하기

src/main/java/sync/slamtalk/mate/service/MatePostService.java, src/main/java/sync/slamtalk/team/controller/TeamMatchingController.java, src/main/java/sync/slamtalk/team/dto/FromTeamFormDTO.java, src/main/java/sync/slamtalk/team/dto/ToTeamFormDTO.java, src/main/java/sync/slamtalk/team/entity/TeamMatching.java
- 팀매칭 게시글 조회 api 주소 변경: api/match/read/{게시글 id}
- 팀매칭 대결 인원 String으로 수정
- skillLevelList, skillLevel 통일
- teamApplicantsDto 에서 teamApplicants로 수정
- 메이트찾기 상세페이지 조회할때 skillLevel 필드 추가
closed #182
=> 프론트엔드 수정 요청 반영

src/main/java/sync/slamtalk/user/controller/AuthController.java, src/main/java/sync/slamtalk/user/service/AuthService.java
- 백엔드 개발용으로 이메일 검증 없이 회원가입을 이용할 수 있도록 /api/test/sign-up을 추가하였습니다.
- 기존 /api/sign-up 대신에 /api/test/sign-up을 사용해주세요!
resolved : #178
=> refactor: 로컬 개발용 회원가입 api 추가했습니다

src/main/java/sync/slamtalk/mate/dto/MatePostToDto.java, src/main/java/sync/slamtalk/mate/mapper/EntityToDtoMapper.java
-  메이트찾기 목록 조회할때 프론트엔드로 전송하는 dto의 필드명 skillList를 skillLevelList로 수정함.
closed #185
=> dto 필드명 수정

src/main/java/sync/slamtalk/mate/entity/Participant.java, src/main/java/sync/slamtalk/team/entity/TeamApplicant.java, src/main/java/sync/slamtalk/team/error/TeamErrorResponseCode.java, src/main/java/sync/slamtalk/team/service/TeamMatchingService.java
- 취소했던 신청자가 다시 신청할 때 WAITING 상태로 복구하도록 로직 수정(WAITING 외 다른 신청 상태에선 CANCELED 상태로 변경 못함)
- 모집 완료 api 요청 시 성공적이면 해당 모집 글 COMPLETED 상태로 변경
- 신청자를 수락할 때 신청자의 적합성 여부 검사 임시 중단(주석 처리)
closed #189
=> 테스트 를 위한 일부 로직 주석 처리 및 상대팀 매칭 신청자의 CANCELED 조건 변경

src/main/java/sync/slamtalk/mate/repository/MatePostRepository.java, src/main/java/sync/slamtalk/team/repository/TeamMatchingRepository.java, src/main/java/sync/slamtalk/user/dto/response/UserDetailsMyInfo.java, src/main/java/sync/slamtalk/user/dto/response/UserDetailsOtherInfo.java, src/main/java/sync/slamtalk/user/service/UserService.java
- getMateCount : 유저가 Mate 매칭 상태가 Completed에 참여한 개수를 구하는 메서드
- getTeamCount : 유저가 Team 매칭 상태가 Completed에 참여한 개수를 구하는 메서드
- MatePostRepository
- 매칭상태가 COMPLETE이고 게시자가 userId인 것의 개수를  구하는 메서드 추가
- 매칭상태가 COMPLETE이고 참여자 상태가 accepted 상태인 참여자 개수를 구하는 메서드 추가
- TeamMatchingRepository 에 쿼리를 추가했습니다
-   - 매칭상태가 COMPLETE이고 게시자가 userId인 것의 개수를  구하는 메서드 추가
- 매칭상태가 COMPLETE이고 참여자 상태가 accepted 상태인 참여자 개수를 구하는 메서드 추가
- Mate와 TeamMatching 부분 Repository를 수정하였습니다!
resolved : #80
=> #80 feat : 마이페이지 팀매칭 개수, 상대팀 매칭 개수 구하는 로직 추가 

src/main/java/sync/slamtalk/security/jwt/JwtTokenProvider.java, src/main/java/sync/slamtalk/user/service/AuthService.java
[AuthService - login 메서드] 
- refactor : 리프레시 토큰 업데이트 하는 로직 추가
- 기존에 refreshToken이 업데이트가 되지않는 현상이 있어서 수정하였습니다
[JwtTokenProvider - generateNewAccessToken 메서드]
- refactor : NPE 발생을 잡기 위한 리팩터링
- user != null 이 아닐 경우만 권한 정보 가져가져와서 토큰을 반환하고 아닐 경우는 Option.empty를 반환하게끔 리팩터링
resolved : #195
=> #195 리프레시 토큰 업데이트 하는 로직 및 NPE 뜨던 오류 해결

src/main/java/sync/slamtalk/security/config/SecurityConfig.java
원인 : 에러 메시지에 따르면, SecurityConfig 클래스의 filterChain 메서드에서 발생한 문제로 보입니다. 구체적으로는 ROLE_ADMIN이 ROLE_로 시작하는데, 이는 hasAnyRole을 사용할 때 ROLE_이 자동으로 붙기 때문에 문제가 발생
해결 : 이 문제를 해결하기 위해서  hasAnyAuthority는 ROLE_을 자동으로 추가하지 않으므로 이러한 충돌을 방지할 수 있습니다.
resolved : #197
=> #197 fit : admin 권한 설정 수정

src/main/java/sync/slamtalk/mate/controller/MatePostController.java, src/main/java/sync/slamtalk/mate/dto/response/MyMateListRes.java, src/main/java/sync/slamtalk/mate/mapper/EntityToDtoMapper.java, src/main/java/sync/slamtalk/mate/repository/MatePostRepository.java, src/main/java/sync/slamtalk/mate/service/MatePostService.java, src/main/java/sync/slamtalk/team/controller/TeamMatchingController.java, src/main/java/sync/slamtalk/team/dto/response/MyTeamMatchingListRes.java, src/main/java/sync/slamtalk/team/repository/TeamMatchingRepository.java, src/main/java/sync/slamtalk/team/service/TeamMatchingService.java, src/main/java/sync/slamtalk/user/controller/UserController.java, src/main/java/sync/slamtalk/user/dto/response/UserSchedule.java, src/main/java/sync/slamtalk/user/service/UserService.java
[임박한 약속 리스트 api]
- /api/user/scheduleList
- 현재 날짜를 기준으로 이후로 내가 참여한 모든 임박한 약속 리스트를 전달
- 기능 설명 : 내가 쓴 메이트 찾기/ 내가 참여한 메이트의 상태가 COMPLETED이고 현재날짜 및 시간 이후의 글을 찾는 메서드
- 참여자일 경우 상태가 ACCEPTED 인 글만 반환한다.
[나의 메이트 찾기 리스트 조회 api]
- /api/mate/my-list
- 내가 참여한 모든 매칭 리스트를 전달
- 기능 설명 : 내가 쓴 메이트 찾기/ 내가 참여한 메이트 등 모든 메이트의 정보를 반환한다.
[나의 상태팀 매칭 리스트 조회 api]
- /api/match/my-list
- 내가 참여한 모든 매칭 리스트를 전달
- 기능 설명 : 내가 쓴 메이트 찾기/ 내가 참여한 메이트 등 모든 메이트의 정보를 반환한다.
resolved : #194
=> #194 MYP15, MYP16 내가 참석한 팀 매칭 내역, 농구 메이트 내역, 임박한 매칭 전달하기!

src/main/java/sync/slamtalk/chat/redis/RedisService.java, src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
- 과거 내역 가져오는 메서드에 @Transactional 어노테이션추가
- 채팅방 과거 내역 요청 시 메세지 누락 문제 해결 시도(readIndex 까지 포함해서 과거내역 반환)
=> 과거 내역 가져오기 메세지 누락 문제 해결 시도

src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
- 채팅방 과거 내역 요청 시 메세지 누락 문제 해결 시도(메세지 저장하는 로직에도 @Transactional 추가)
=> bug : 채팅방 과거 내역 요청 시 메세지 누락 문제 해결 시도(메세지 저장하는 로직에도 @Transactional 추가)

src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
- 채팅방 과거 내역 요청 시 메세지 누락 문제 해결 시도(메세지 db 저장 시 Redis 에도 저장하게 함)
=> bug : 채팅방 과거 내역 요청 시 메세지 누락 문제 해결 시도(메세지 db 저장 시 Redis 에도 저장하게 함)

src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
- 메세지저장시 redis에 먼저저장되도록함, `@Transactional`어노테이션 제거
=> bug : 채팅방 과거 내역 요청 시 메세지 누락 문제 해결 시도

src/main/java/sync/slamtalk/security/oauth2/handler/OAuth2LoginFailureHandler.java, src/main/java/sync/slamtalk/security/oauth2/handler/OAuth2LoginSuccessHandler.java
- 소셜 로그인 성공 및 실패  리다이렉트 url을 프론트 서버로 변경
resolved : #226
=> #226 refactor : 소셜 로그인 성공 및 실패 시 리다이렉트 url을 프론트 서버 url로 리팩터링

src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
- 채팅 과거 내역 요청 에러 수정
- readIndex가 0이면 (초기값에서 업데이트되지 않았으면) null 값 으로 반환하여 응답
closed #247
=> #247 과거 내역 요청 에러 수정

src/main/java/sync/slamtalk/security/config/SecurityConfig.java, src/main/java/sync/slamtalk/user/controller/UserController.java
- 상대방 유저 프로필 보는 기존 /api/user/{userId}/other-info 를 다음과 같이 수정하려고 합니다.
- 게스트 권한 설정
- /api/user/other-info/{userId} GET Method
- 기존에 받는 값을 동일.
- yml 파일이 변경되었습니다
- 프론트 분들 url이 다음과 같이 수정되었습니다
-/api/user/{userId}/other-info => /api/user/other-info/{userId}
resolved : #244
=> #244 상대방 프로필 보기 게스트  권한 설정

src/main/java/sync/slamtalk/user/controller/UserController.java, src/main/java/sync/slamtalk/user/service/UserService.java
- /api/user/update 를 patch 에서 post 로 수정
- 이유 :  multipart/form 데이터 형식은 주로 파일 업로드와 같은 전체 데이터를 보낼 때 사용됩니다. 이러한 두 가지는 의미적으로 맞지 않아서
- 파일이 이미지가 존재하지 않으면 이미지 업데이트 안하도록 설정
- 각각의 필드(닉네임, 자기소개, 포지션, 실력)가 기존 값이랑 동일하면 변경되지 않도록 설정
resolved : #250
=> #250 유저 마이페이지 수정 로직 리팩터링 

build.gradle, src/main/java/sync/slamtalk/chat/dto/Response/ChatRoomDTO.java, src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java, src/main/java/sync/slamtalk/common/s3bucket/repository/AwsS3RepositoryImpl.java, src/test/java/sync/slamtalk/chat/repository/UserChatRoomRepositoryTest.java
- 채팅리스트에서 팀매칭 채팅방 상대방 유저의 이름이 아니라 채팅방 이름자체가 뜨도록 수정
- 채팅방 리스트 api 코드 수정
- s3bucket 에 허용되는 파일 확장자 추가
=> #241 채팅 리스트 로직 수정, s3bucket 에 저장가능한 이미지 확장자 추가

src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
- 모두 삭제하지 않은 경우에만(isDelete = false) 기존의 채팅방 아이디 반환하도록 수정
=> #241 채팅방 중복 생성 버그 수정

src/main/java/sync/slamtalk/chat/controller/ChatController.java, src/main/java/sync/slamtalk/chat/dto/ChatErrorResponseCode.java, src/main/java/sync/slamtalk/chat/redis/RedisService.java, src/main/java/sync/slamtalk/chat/service/ChatService.java, src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
- ChatErrorResponseCode 에서 클래스 값 접근 메서드 반환값 수정
- 채팅방 접속 후 과거 내역 추가 요청 시 lastMessageId 를 기준으로 페이징
- 과거 내역 요청 api 파라미터 변경, 관련 서비스 코드 변경
=> bug : ChatErrorResponseCode 메소드 수정,과거 내역 추가 요청 컨트롤러/서비스코드 수정

src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java, src/main/java/sync/slamtalk/chat/dto/request/ChatMessageDTO.java, src/main/java/sync/slamtalk/chat/dto/response/ChatRoomDTO.java, src/main/java/sync/slamtalk/chat/service/ChatService.java, src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java, src/main/java/sync/slamtalk/notification/model/NotificationContent.java
‼️‼️ @sbslc2000 님이 작성한 코드 수정
NotificationContent 에 BaseEntity 상속
이유 : create_at 사용 시 BaseEntity 상속 필요함, NotificationContent 에는 별도 속성 x
- 채팅방 리스트 API 새로운 메세지 속성 추가
- 채팅 알림(새로운 방 생성, 새로운 메세지 발생)
- 팀매칭 채팅방 유저 프로필 추가
- 과거 메세지 추가적으로 페이징할 경우 중복처리 로직 추가, ChatMessageDTO 수정
=> 채팅방 새로운 메세지 알림 외

src/main/java/sync/slamtalk/security/config/SecurityConstants.java, src/main/java/sync/slamtalk/security/jwt/JwtFilter.java, src/main/java/sync/slamtalk/security/oauth2/handler/OAuth2LoginSuccessHandler.java, src/main/java/sync/slamtalk/security/oauth2/service/CustomOAuth2UserService.java, src/main/java/sync/slamtalk/user/controller/AuthController.java, src/main/java/sync/slamtalk/user/dto/response/UserDetailsOtherInfo.java, src/main/java/sync/slamtalk/user/entity/SocialType.java, src/main/java/sync/slamtalk/user/entity/User.java, src/main/java/sync/slamtalk/user/error/UserErrorResponseCode.java, src/main/java/sync/slamtalk/user/service/AuthService.java, src/main/java/sync/slamtalk/user/service/NicknameService.java, src/main/java/sync/slamtalk/user/service/RevokeSocialLoginService.java, src/test/java/sync/slamtalk/security/oauth2/service/NicknameServiceTest.java
- RDB User 제약조건 변경되었습니다. 
resolved : #321
=> #324 회원 탈퇴 구현 

src/main/java/sync/slamtalk/user/error/UserErrorResponseCode.java, src/main/java/sync/slamtalk/user/service/AuthService.java
- 소셜 타입이 LOCAL 일 경우에만 비밀번호 수정가능하게 그 외는 에러를 던지게끔 요구사항 변경
resolved #337
=> #337  소셜 로그인은 비밀번호 변경 지원 안함.

src/main/java/sync/slamtalk/mate/error/MateErrorResponseCode.java, src/main/java/sync/slamtalk/mate/service/MatePostService.java, src/main/java/sync/slamtalk/team/error/TeamErrorResponseCode.java, src/main/java/sync/slamtalk/team/service/TeamMatchingService.java
- 상대팀매칭 등록 및 수정 시 약속시간 검증 로직 추가
- 팀매칭게시글 등록 및 수정 시 약속시간 검증하는 로직 추가
검증로직 
예약 날짜 또는 시간이 현재 날짜 및 시간보다 이전인 경우 예외를 발생시킵니다.
- 예약 날짜가 현재 날짜보다 이전인 경우 APPOINTMENT_DATE_ERROR 예외가,
- 예약 날짜는 같지만 예약 시작 시간이 현재 시간보다 이전 또는 같은 경우 APPOINTMENT_TIME_ERROR 예외가 발생합니다.
=> [팀매칭/상대팀매칭] 약속시간 검증로직 추가

src/main/java/sync/slamtalk/mate/service/MatePostService.java, src/main/java/sync/slamtalk/team/service/TeamMatchingService.java
=> [팀매칭/메이트매칭] 게시글 시간 검증 로직 수정
