SlamTalk/slam-talk-backend

README.md

docs : README.md

---

README.md

DOCS update

---

src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java
src/main/java/sync/slamtalk/chat/config/StompWebSocketConfig.java
src/main/java/sync/slamtalk/chat/controller/StompChatController.java
src/main/java/sync/slamtalk/chat/dto/ChatMessageDTO.java
src/main/java/sync/slamtalk/chat/dto/ChatRoomDTO.java

> - webSocketConfig(엔드포인트, 메세지브로커설정)
> - 채팅방과 관련된 비즈니스 로직이 포함된 컨트롤러,DTO 작성
> 이전 프로젝트에서 DTO 에 빌더패턴을 쓰지 않아서 Xxx.set 을 남발했던 경험이 있습니다.
> 그래서 ChatMessageDTO에 빌더패턴을 적용해보았습니다.

#10 채팅기능기본설정

---

src/main/java/sync/slamtalk/chat/dto/ChatMessageDTO.java

- ChatMessageDTO 에 어노테이션을 수정했습니다.

refactor : annotation 추가

---

src/main/java/sync/slamtalk/mate/domain/MatePost.java
src/main/java/sync/slamtalk/mate/domain/Member.java
src/main/java/sync/slamtalk/mate/domain/Participant.java

- MatePost, Participant, Member(다른 엔터티를 위한 임시 엔터티) 엔터티 생성함
- 로컬 데이터베이스 내에 테이블이 정상적으로 생성되는 것을 확인함
- Controller와 Service, Repository 계층을 생성하면서 추가적인 메소드 구현 및 보완 작업을 할 예정입니다.

#18 같이하기 관련 엔터티 생성

---

src/main/java/sync/slamtalk/mate/controller/RegisterMatePostController.java
src/main/java/sync/slamtalk/mate/repository/MatePostRepository.java
src/main/java/sync/slamtalk/mate/repository/MemberRepository.java
src/main/java/sync/slamtalk/mate/repository/ParticipantRepository.java
src/main/java/sync/slamtalk/mate/service/RegisterMatePostService.java

- RegisterMatePostController.java, MatePostRepository.java, MemberRepository.java, ParticipantRepository.java, RegisterMatePostService.java 생성
- 기능 구현 전 생성한 파일이 많아 일단 PR을 하였습니다!

#11 메이트 찾기 글쓰기를 위한 Repository, Controller, Service 파일 생성

---

build.gradle
src/main/java/sync/slamtalk/swagger/SwaggerConfig.java
src/main/java/sync/slamtalk/test/Controller.java

- Swagger 사용을 위해 구현체인 springfox 라이브러리 추가
- SwaggerConfig 파일 추가
- test 패키지에 예제 Controller 를 넣어 두었습니다.
- 로컬에서 서버실행 후 http://localhost:8080/swagger-ui/index.html 에 접속하시면 api 문서를 보실 수 있습니다.

#21 Swagger 기본 설정 및 의존성 추가

---

src/main/java/sync/slamtalk/test/Controller.java

- RequestMapping을 안쓰고 잘 못 어노테이션을 넣어서 생긴 오류를 해결
resolved #21

#21 Swagger 모듈 개발 - Controller 수정

---

build.gradle
src/main/java/sync/slamtalk/user/UserRepository.java
src/main/java/sync/slamtalk/user/dto/UserSignUpRequestDto.java
src/main/java/sync/slamtalk/user/entity/SocialType.java
src/main/java/sync/slamtalk/user/entity/User.java
src/main/java/sync/slamtalk/user/entity/UserBasketballPositionType.java
src/main/java/sync/slamtalk/user/entity/UserBasketballSkillLevelType.java
src/main/java/sync/slamtalk/user/entity/UserRole.java

- 유저 엔티티 개발
- 유저 레포 개발
- 유저 dto 개발
- build.gradle 시큐리티 설정
resolved #26

#26 유저 - 엔티티, 레포지토리 생성하기

---

.github/workflows/gradle.yml
build.gradle
src/main/java/sync/slamtalk/security/config/CorsConfig.java
src/main/java/sync/slamtalk/security/config/SecurityConfig.java
src/main/java/sync/slamtalk/security/dto/JwtTokenResponseDto.java
src/main/java/sync/slamtalk/security/jwt/JwtAccessDeniedHandler.java
src/main/java/sync/slamtalk/security/jwt/JwtAuthenticationEntryPoint.java
src/main/java/sync/slamtalk/security/jwt/JwtFilter.java
src/main/java/sync/slamtalk/security/jwt/JwtTokenProvider.java
src/main/java/sync/slamtalk/security/service/CustomUserDetailsService.java
src/main/java/sync/slamtalk/security/utils/CookieUtil.java
src/main/java/sync/slamtalk/swagger/test/Controller.java
src/main/java/sync/slamtalk/user/UserRepository.java
src/main/java/sync/slamtalk/user/UserService.java
src/main/java/sync/slamtalk/user/controller/UserController.java
src/main/java/sync/slamtalk/user/dto/UserLoginRequestDto.java
src/main/java/sync/slamtalk/user/dto/UserSignUpRequestDto.java
src/main/java/sync/slamtalk/user/entity/User.java
src/main/java/sync/slamtalk/user/error/UserErrorResponseCode.java

-  jwt 토큰을 사용한 일반 회원가입, 로그인 구현하기
-  시큐리티 구현하기
-  시큐리티 필터를 통하여 역할에 따른 인증 인가 구현
- MERGE 이전에 yml 파일 업데이트 해야합니다! 리뷰 후 바로 MERGE 하지 말아주세요!

#26 유저 모듈 개발 

---

src/main/java/sync/slamtalk/security/config/CorsConfig.java
src/main/java/sync/slamtalk/security/config/SecurityConfig.java
src/main/java/sync/slamtalk/security/dto/JwtTokenResponseDto.java
src/main/java/sync/slamtalk/security/jwt/JwtFilter.java
src/main/java/sync/slamtalk/security/jwt/JwtTokenProvider.java
src/main/java/sync/slamtalk/security/utils/CookieUtil.java
src/main/java/sync/slamtalk/user/UserController.java
src/main/java/sync/slamtalk/user/UserService.java

- AccessToken 헤더로 받게끔 설정
- RefreshToken 쿠키로 받게끔 설정하기
- AccessToken  만료시 RefreshToken 재발급 api 개발
- https 적용을 위한 security config 파일 수정
- :rotating_light: merge 이전에 말해주세요 추가 설정해야 할 것들이 있습니다!

#49 AccessToken 헤더로 받게끔 설정, RefreshToken 쿠키로 받게끔 설정하기

---

src/main/java/sync/slamtalk/map/controller/BasketballCourtController.java
src/main/java/sync/slamtalk/map/dto/BasketballCourtDto.java
src/main/java/sync/slamtalk/map/entity/BasketballCourt.java
src/main/java/sync/slamtalk/map/mapper/BasketballCourtMapper.java
src/main/java/sync/slamtalk/map/service/BasketballCourtService.java
src/main/java/sync/slamtalk/map/service/ReportBasketballCourtService.java

-  #42  
-  dto -> entity 변환 mapper 추가
- chatroom_id 필드 null 값 허용
- 제보 받은 농구장 정보 저장 구현 
resolved #42

#42 제보 받은 농구장 정보 저장

---

src/main/java/sync/slamtalk/security/jwt/JwtTokenProvider.java

- JwtTokenProvider에서 엑세스 토큰 추출하는 메서드 리팩터링
- stompExtractUserIdFromToken 메서드 추가
resolved : #52

#52 refactor 웹소켓 STOMP 사용시 accessToken에서 userId 추출하는 메서드 리팩토링

---

src/main/java/sync/slamtalk/map/dto/BasketballCourtDto.java
src/main/java/sync/slamtalk/map/entity/BasketballCourt.java
src/main/java/sync/slamtalk/map/mapper/BasketballCourtMapper.java

-  #57  
- 주소, 전화번호, 홈페이지, 편의시설 필드 추가
- 개방시간, 사용료 -> Boolean 변경
- 관련 dto, mapper 수정
closed #57

#57 농구장 테이블 필드 추가 및 수정

---

src/main/java/sync/slamtalk/security/config/CorsConfig.java

- Cors 설정오류로 인해 클라이언트 헤더에 값이 담기도록 수정
- 해당 오류가 시급한 건입니다.
resolved : #66

#66 bug : cors 에러 수정

---

src/main/java/sync/slamtalk/common/BaseEntity.java

- BaseEntity 상속 후 필드 안생기는 문제 해결 
- softDelete 구현할 수 있도록 관련 필드 추가
closed #64

#64 modified : BaseEntity

---

.github/workflows/gradle.yml

- application-oauth.yml 추가하는 github actions 로직 리팩터링
resolved : #70

#70 refactor : github-acionts 수정

---

src/main/java/sync/slamtalk/security/oauth2/service/CustomOAuth2UserService.java

- refactor : bug 수정 Transaction 어노테이션 추가
resolved : #72

#72 refactor : bug 수정 Transaction 어노테이션 추가

---

src/main/java/sync/slamtalk/security/jwt/JwtFilter.java

- jwtFilter 안거치는 exception경로를 지정하고 필터단에 리팩터링 하는 로직 추가
resolved: #75

#75 Refactor  jwt filter

---

src/main/java/sync/slamtalk/map/controller/AdminBasketballCourtController.java
src/main/java/sync/slamtalk/map/entity/BasketballCourt.java
src/main/java/sync/slamtalk/map/repository/BasketballCourtRepository.java
src/main/java/sync/slamtalk/map/service/AdminBasketballCourtService.java
src/main/java/sync/slamtalk/map/service/BasketballCourtService.java
src/main/java/sync/slamtalk/map/service/ReportBasketballCourtService.java

- 농구장 제보 목록 조회
- 특정 농구장 정보 입력 및 관리자 수락
> entity 클래스에서 무분별한 setter를 지양하며 특정 필드 값을 업데이트하기 위해서 update 메서드를 작성했는데 코드가 너무 난잡해 보이나요?

#63 관리자 제보 목록 조회 및 수락 기능 추가

---

build.gradle
src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java
src/main/java/sync/slamtalk/chat/config/StompErrorHandler.java
src/main/java/sync/slamtalk/chat/controller/ChatController.java
src/main/java/sync/slamtalk/chat/entity/Messages.java
src/main/java/sync/slamtalk/chat/redis/RedisConfig.java
src/main/java/sync/slamtalk/chat/redis/RedisController.java
src/main/java/sync/slamtalk/chat/redis/RedisService.java
src/main/java/sync/slamtalk/chat/repository/MessagesRepository.java
src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
src/main/java/sync/slamtalk/common/BaseEntity.java
src/test/java/sync/slamtalk/chat/redis/RedisServiceTest.java
src/test/java/sync/slamtalk/chat/repository/UserChatRoomRepositoryTest.java

- build.gradle 수정이 있었습니다. (testcode 관련 의존성, Redis 관련 의존성 추가됨)
- BaseEntity 에 시간 형식을 수정하였습니다
- BaseEntity 에 삭제여부 타입을 (boolean -> Boolean) 수정하였습니다.
>  👀참고해주세요 
- boolean: 성능이 중요하고, `null` 값이 필요 없는 경우에 사용합니다.
예: 조건문, 루프 제어 등
- Boolean:`null` 값을 허용해야 하거나, 컬렉션에 boolean 값을 저장해야 하는 경우에 사용합니다.
예: 데이터베이스에서 null을 허용하는 boolean 필드, 제네릭 컬렉션 등
closed #68

#68 Redis 설정파일 작성, 리팩토링

---

src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java
src/main/java/sync/slamtalk/chat/controller/ChatController.java
src/main/java/sync/slamtalk/chat/redis/RedisController.java
src/main/java/sync/slamtalk/chat/repository/MessagesRepository.java
src/main/java/sync/slamtalk/chat/service/ChatService.java
src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
src/main/java/sync/slamtalk/common/BaseEntity.java

- BaseEntity 에 isDelete 값을 가져오는 get메서드 추가했습니다.
closed #45

#45 채팅퇴장/뒤로가기 서비스,컨트롤러 작성

---

build.gradle
src/main/java/sync/slamtalk/common/ErrorResponseCode.java
src/main/java/sync/slamtalk/common/s3bucket/FileUploadController.java
src/main/java/sync/slamtalk/common/s3bucket/config/CommonUtils.java
src/main/java/sync/slamtalk/common/s3bucket/config/S3Config.java
src/main/java/sync/slamtalk/common/s3bucket/repository/AwsS3Repository.java
src/main/java/sync/slamtalk/common/s3bucket/repository/AwsS3RepositoryImpl.java

- 👀 같이 리뷰 필요
> `fileUploaedcontroller.java`는 연동 테스트 겸 레퍼런스 용도로 넣어놓았습니다. 
저는 하나의 controller 를 두고 사용하는 것보다  도메인별로 repository를 자동주입하여 직접 사용하는 방식이 더 확장성을 고려한 코드라고 생각하는데 다른 분들은 어떻게 생각하시나요?
closed #84

#84 s3bucket 연동

---

src/main/java/sync/slamtalk/map/controller/BasketballCourtController.java

-  농구장 목록 조회 및 상세 정보 조회 게스트 Tag 추가
>
closed #89

#89 Map 게스트 Swagger Tag 추가

---

src/main/java/sync/slamtalk/user/dto/UserLoginResponseDto.java
src/main/java/sync/slamtalk/user/service/AuthService.java

- 이번 요청으로 로그인/ 회원가입/ 리프레시 토큰 시 body 부분에 반환타입이 변경되었습니다.
[UserLoginResponseDto]
- 기존
- firstLoginCheck
- 변경 후
- userId,  nickname,  imageUrl, firstLoginCheck을 보내주게끔 설계했습니다!
- MERGE 는 1월 31일 오전중에 해주시면 감사하겠습니다!
resolved: #97

#97 UserLoginResponseDto 반환 값 추가

---

src/main/java/sync/slamtalk/map/controller/BasketballCourtController.java

- 전체 조회 -> /api/map/courts
- 상세 조회 -> /api/map/courts/{courtId}
> 엔드포인트 위와 같이 수정하면 괜찮을까요?
closed #100

#100 Map 게스트 기능을 위한 엔드포인트 수정

---

src/main/java/sync/slamtalk/map/controller/BasketballCourtController.java
src/main/java/sync/slamtalk/map/dto/BasketballCourtDto.java
src/main/java/sync/slamtalk/map/entity/BasketballCourt.java
src/main/java/sync/slamtalk/map/mapper/BasketballCourtMapper.java
src/main/java/sync/slamtalk/map/service/ReportBasketballCourtService.java

- 농구장 테이블 제보자ID 필드 추가 & 제보자 id 저장
- 
- 봉승님 요구사항이기에 봉승님만 확인해 주시면 Merge 하겠습니다!

#104 농구장 테이블 제보자ID 필드 추가 & 제보자 id 저장

---

src/main/java/sync/slamtalk/security/jwt/JwtTokenProvider.java

- 클라이언트가 stomp 헤더에 보내주는 accessToken을 검증 할 때 Bearer 인증타입을 보게끔 리팩터링 했습니다!
인증타입 쓰는 이유
- JWT 혹은 OAuth에 대한 토큰을 사용한다. (RFC 6750) 를 의미 하기 때문에 명시적으로 사용하고 있습니다!
resolved : #108

#108 refactor : Stomp 메서드 Bearer 인증 타입 설정 추가

---

src/main/java/sync/slamtalk/user/dto/UserUpdatePositionAndSkillRequestDto.java
src/main/java/sync/slamtalk/user/service/UserService.java

- UserUpdatePositionAndSkillRequestDto 에서 enum 타입으로 선언해서 Controller 단에서 요청 body를 enum으로 바로 받을 수 있게 끔 리팩터링 했습니다
-  @Enumerated(EnumType.STRING) 사용했습니다
resolved : #99

#99 refactor : 유저 최초 정보수집 enum 으로 받게끔 리팩터링

---

src/main/java/sync/slamtalk/mate/controller/MatePostController.java
src/main/java/sync/slamtalk/mate/entity/Participant.java
src/main/java/sync/slamtalk/mate/entity/SkillLevelType.java
src/main/java/sync/slamtalk/mate/mapper/MatePostEntityToDtoMapper.java
src/main/java/sync/slamtalk/mate/service/MatePostService.java
src/main/java/sync/slamtalk/mate/service/ParticipantService.java
src/main/java/sync/slamtalk/team/controller/TeamMatchingController.java
src/main/java/sync/slamtalk/team/dto/FromApplicantDto.java
src/main/java/sync/slamtalk/team/dto/FromTeamFormDTO.java
src/main/java/sync/slamtalk/team/dto/ToApplicantDto.java
src/main/java/sync/slamtalk/team/dto/ToTeamFormDTO.java
src/main/java/sync/slamtalk/team/entity/TeamApplicant.java
src/main/java/sync/slamtalk/team/entity/TeamApplyStatusType.java
src/main/java/sync/slamtalk/team/entity/TeamMatching.java
src/main/java/sync/slamtalk/team/repository/TeamMatchingRepository.java
src/main/java/sync/slamtalk/team/service/TeamMatchingService.java

-  프론트엔드로부터 받는 날짜 타입 변경 및 추가에 따른 팀매칭 엔티티와 관련 dto 수정
-  팀매칭 게시글 목록 조회할 때 소프트 딜리트 처리된 게시글은 제외하도록 수정.
closed #114

#114 날짜 타입 관련 변경 및 팀매칭 삭제 기능 오류 해결

---

src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java
src/main/java/sync/slamtalk/chat/controller/ChatController.java
src/main/java/sync/slamtalk/chat/controller/StompChatController.java
src/main/java/sync/slamtalk/chat/dto/Request/ChatMessageDTO.java
src/main/java/sync/slamtalk/chat/dto/Response/ChatRoomDTO.java
src/main/java/sync/slamtalk/chat/entity/UserChatRoom.java
src/main/java/sync/slamtalk/chat/service/ChatService.java
src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
src/main/java/sync/slamtalk/common/ApiResponse.java

- API 수정
- response dto 에 상대방 아이디 필드 추가
- request dto 에 작성 시간 추가
- SUBSCRIBE 에서 usercharoom 생성하는 로직 수정
- BaseEntity 에서 isDelete 초기값을 false 로 지정(원래는 null)
closed #117

#117 API 수정 외

---

src/main/java/sync/slamtalk/chat/controller/ChatController.java
src/main/java/sync/slamtalk/map/controller/BasketballCourtController.java
src/main/java/sync/slamtalk/security/jwt/JwtTokenProvider.java
src/main/java/sync/slamtalk/security/oauth2/handler/OAuth2LoginSuccessHandler.java
src/main/java/sync/slamtalk/swagger/test/Controller.java
src/main/java/sync/slamtalk/user/controller/UserController.java
src/main/java/sync/slamtalk/user/service/UserService.java

- localhost:3000?loginSuccess=true 로 소셜로그인 리다이렉트 url 수정하기
- @Authentication Long userId 로 수정
- 기존 AccessToken 추출 시 userDB 조회하는 로직 제외
- 수정 : @authentication 사용시 Long userId 반환하도록 설정
- 다음 파일 리스트를 참고해주세요!
[수정에 포함되는 파일 리스트]
UserController
ChatController
BasketballCourtController
Swagger - Controller

#119 Refactor/119 oauth

---

src/main/java/sync/slamtalk/user/controller/UserController.java
src/main/java/sync/slamtalk/user/entity/User.java
src/main/java/sync/slamtalk/user/entity/UserAttendance.java
src/main/java/sync/slamtalk/user/error/UserErrorResponseCode.java
src/main/java/sync/slamtalk/user/repository/UserAttendanceRepository.java
src/main/java/sync/slamtalk/user/service/UserService.java

- 출석은 하루에 한 번만 가능하다.
- 유저 레벨 점수가 +1 올라간다.
- 출석 테이블 생성
- 하루에 한번만 출석되도록 하는 로직 추가하기!
- 레벨 점수 1 상승 로직 추가하기
resolved : #120

#120 feat : 유저 출석 기능 구현

---

src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java

- 채팅방 아예 나가기 (==삭제) 하지 않은 채팅방만 보내주기 
closed #132

#132 채팅리스트 로직 수정

---

src/main/java/sync/slamtalk/user/controller/UserController.java
src/main/java/sync/slamtalk/user/dto/UpdateUserDetailInfoRequestDto.java
src/main/java/sync/slamtalk/user/entity/User.java
src/main/java/sync/slamtalk/user/service/UserService.java
src/test/java/sync/slamtalk/mate/repository/MatePostRepositoryTest.java
src/test/java/sync/slamtalk/user/service/UserServiceTest.java

- 이미지 첨부 시 이미지 저장및 업데이트 로직
- 그 이외에 수정가능한 모든 것 PATCH로 받기
resolved #125

#125 feat : 유저 마이페이지 수정 기능

---

src/main/java/sync/slamtalk/security/oauth2/handler/OAuth2LoginSuccessHandler.java
src/main/java/sync/slamtalk/user/service/AuthService.java

-  최초회원가입 여부 파라미터에 전달하게끔 리팩터링
- 소셜 로그인 시에 &firstLoginCheck=true 도 함께 전송하는 로직으로 리팩터링하기
resolved : #134

#134 refactor : 최초회원가입 여부 파라미터에 전달하게끔 리팩터링

---

src/main/java/sync/slamtalk/map/controller/BasketballCourtController.java
src/main/java/sync/slamtalk/map/dto/BasketballCourtDto.java
src/main/java/sync/slamtalk/map/dto/BasketballCourtSummaryDto.java
src/main/java/sync/slamtalk/map/mapper/BasketballCourtMapper.java
src/main/java/sync/slamtalk/map/service/BasketballCourtService.java

#147 농구장 반환 값 수정

---

src/main/java/sync/slamtalk/user/dto/UserDetailsMyInfoResponseDto.java

- /api/user/my-info API 호출될 때 role도 함께 보내주기
- role이 추가되었습니다.

feat: 관리자 페이지를 위해 Role 추가

---

src/main/java/sync/slamtalk/chat/redis/RedisService.java

- getData : 인증코드 있는지 확인하는 메서드
- setData
- setDataExpire
- deleteData

#146 feat: redis 이메일 인증관련 service 메서드 추가

---

src/main/java/sync/slamtalk/community/controller/CommentController.java
src/main/java/sync/slamtalk/community/dto/CommentCreateRequestDTO.java
src/main/java/sync/slamtalk/community/dto/CommentResponseDTO.java
src/main/java/sync/slamtalk/community/dto/CommunityErrorResponseCode.java
src/main/java/sync/slamtalk/community/entity/Comment.java
src/main/java/sync/slamtalk/community/entity/Community.java
src/main/java/sync/slamtalk/community/mapper/CommentMapper.java
src/main/java/sync/slamtalk/community/repository/CommentRepository.java
src/main/java/sync/slamtalk/community/service/CommentService.java
src/main/java/sync/slamtalk/community/service/CommunityService.java

#156 댓글 crud

---

src/main/java/sync/slamtalk/security/config/SecurityConfig.java
src/main/java/sync/slamtalk/security/oauth2/handler/OAuth2LoginFailureHandler.java
src/main/java/sync/slamtalk/user/UserRepository.java

-  회원탈퇴시 7일동안 재가입 및 소셜로그인 불가능하게끔 로직 수정
resolved : #162

#162 refactor : 회원탈퇴시 7일동안 재가입 및 소셜로그인 불가능하게끔 로직 수정

---

src/main/java/sync/slamtalk/community/controller/CommunityController.java
src/main/java/sync/slamtalk/map/controller/BasketballCourtController.java
src/main/java/sync/slamtalk/map/mapper/BasketballCourtMapper.java
src/main/java/sync/slamtalk/map/service/ReportBasketballCourtService.java

#165 농구장 이미지 업로드 구현

---

src/main/java/sync/slamtalk/team/service/TeamMatchingService.java

충돌나는 부분 수정

---

src/main/java/sync/slamtalk/user/service/AuthService.java

- 운영환경에서는 해제할 필요가 있음!
resolved : #178

#178 refactor: 회원가입 시 redis를 확인하는 로직 삭제

---

src/main/java/sync/slamtalk/team/controller/TeamMatchingController.java
src/main/java/sync/slamtalk/team/service/TeamMatchingService.java

팀매칭 서비스 계층 충돌 해결

---

src/main/java/sync/slamtalk/community/entity/CommunityImage.java
src/main/java/sync/slamtalk/community/service/CommunityService.java
src/main/java/sync/slamtalk/map/entity/BasketballCourt.java

#161 게시판 이미지 업로드 검증 로직

---

src/main/java/sync/slamtalk/security/config/SecurityConfig.java

- securityConfig에 제외경로 추가
resolved : #178

#178 refactor: securityConfig에 제외 경로 추가

---

src/main/java/sync/slamtalk/mate/service/MatePostService.java
src/main/java/sync/slamtalk/team/controller/TeamMatchingController.java
src/main/java/sync/slamtalk/team/dto/ToTeamFormDTO.java
src/main/java/sync/slamtalk/team/entity/TeamMatching.java
src/main/java/sync/slamtalk/team/error/TeamErrorResponseCode.java
src/main/java/sync/slamtalk/team/service/TeamMatchingService.java

> 이번 PR에서 작업한 내용을 간략히 설명해주세요
- dto로 전달하는 필드명 추가 및 변경, api 요청 테스트 확인
closed #187

dto로 전달하는 필드명 추가 및 변경, api 요청 테스트 확인

---

src/main/java/sync/slamtalk/security/config/SecurityConfig.java

- fit : admin 권한 설정 변경
resolved : #197

#197 fit : admin 권한 설정 변경

---

src/main/java/sync/slamtalk/chat/dto/ChatErrorResponseCode.java
src/main/java/sync/slamtalk/chat/dto/Request/ChatCreateDTO.java
src/main/java/sync/slamtalk/chat/entity/ChatRoom.java
src/main/java/sync/slamtalk/chat/entity/UserChatRoom.java
src/main/java/sync/slamtalk/chat/repository/ChatRoomRepository.java
src/main/java/sync/slamtalk/chat/repository/UserChatRoomRepository.java
src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java

- 채팅방 중복 생성 방지 로직을 추가하였습니다.
- 채팅방 생성 요청 api 변경
- UserChatRoom, ChatRoom entity 에 필드 추가
closed #191

#191 채팅방 중복 생성 방지 로직 추가

---

src/main/java/sync/slamtalk/chat/controller/StompChatController.java
src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
src/main/java/sync/slamtalk/common/BaseEntity.java

- /sub/chat/bot 이라는 destination 추가
- 추가된 경로로 메세지 발행할 떄 최초 입장,퇴장 검증하여 Message 다르게 발행하는 로직 추가
- 퇴장 후 채팅리스트 상에서 사라지는 거까지 확인함
closed #192

#192 채팅방 입장,퇴장 메세지 작업

---

src/main/java/sync/slamtalk/chat/controller/StompChatController.java

- StompMessageController 에 @Transactional 추가

#192 refactor : @Transactional추가

---

src/main/java/sync/slamtalk/mate/service/MatePostService.java
src/main/java/sync/slamtalk/team/service/TeamMatchingService.java
src/main/java/sync/slamtalk/user/service/UserService.java

- 약속 날짜, 시작 일순 으로 오름차순으로 정렬해서 보내주도록 개발
- MatePostService 
- TeamMatchingService 
코드 수정 했습니다
resolved : #194

#194 시간 순으로 배열을 보내주게끔 설계하기

---

src/main/java/sync/slamtalk/mate/dto/UnrefinedMatePostDTO.java
src/main/java/sync/slamtalk/mate/entity/ApplyStatusType.java
src/main/java/sync/slamtalk/mate/mapper/EntityToDtoMapper.java
src/main/java/sync/slamtalk/mate/repository/QueryRepository.java
src/main/java/sync/slamtalk/mate/service/MatePostService.java
src/main/java/sync/slamtalk/team/entity/TeamApplicant.java
src/main/java/sync/slamtalk/team/service/TeamMatchingService.java

- 포지션 필터링 시 각각의 포지션 선택에 자리가 남았을 경우의 포지션 무관(UNSPECIFIED)도 포함
- 메이트찾기 목록 조회 시 약속 시간이 지난 글들은 제외하도록 수정함.
- 신청자 지원 할때 적합성 여부 주석 처리.
- 기타 불필요한 코드를 걸러내기 위한 코드 수정.
closed #208

프론트엔드와 소통을 포함한 기타 수정사항 반영

---

src/main/java/sync/slamtalk/map/repository/BasketballCourtRepository.java
src/main/java/sync/slamtalk/user/dto/response/UserDetailsMyInfo.java
src/main/java/sync/slamtalk/user/dto/response/UserDetailsOtherInfo.java
src/main/java/sync/slamtalk/user/entity/User.java
src/main/java/sync/slamtalk/user/service/UserService.java
src/main/java/sync/slamtalk/user/utils/UserLevelScore.java

- 유저 레벨 관련 클래스를 utils 패키지로 분리하였습니다.
- 내가 제보한 승인된 농구장 개수를 구해서 User level 에 개당 30점씩 반영하였습니다.
- BasketballCourtRepository에서 내가 제보하고 관리자 승인 상태가 ACCEPTED인 개수를 구하는 메서드를 추가
- BasketballCourtRepository 코드 추가
resolved : #80

#80 내가 제보한 승인된 농구장 개수 구해서 레벨에 반영하는 로직 추가

---

src/main/java/sync/slamtalk/map/controller/BasketballCourtController.java
src/main/java/sync/slamtalk/map/dto/BasketballCourtErrorResponse.java
src/main/java/sync/slamtalk/map/dto/BasketballCourtReportResponseDTO.java
src/main/java/sync/slamtalk/map/dto/BasketballCourtReportSummaryDTO.java
src/main/java/sync/slamtalk/map/entity/BasketballCourt.java
src/main/java/sync/slamtalk/map/mapper/BasketballCourtMapper.java
src/main/java/sync/slamtalk/map/repository/BasketballCourtRepository.java
src/main/java/sync/slamtalk/map/service/BasketballCourtService.java
src/main/java/sync/slamtalk/map/service/ReportBasketballCourtService.java
src/main/java/sync/slamtalk/user/service/UserService.java

- 이용자가 제보한 농구장 정보 조회/수정 기능 구현
>

#202 제보한 농구장 조회/수정 기능

---

src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java

#212 bug : 채팅방생성에러메세지해결시도

---

src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java

- 채팅방 뒤로가기 시 readIndex 업데이트 안되는 문제 해결 시도

채팅방 뒤로가기 시 readIndex 업데이트 안되는 문제 해결 시도

---

src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java

- saveReadIndex, getMessages 메서드에 @Transactional 어노테이션추가함

bug : 채팅방나가시 시 readIndex update 안되는 문제 해결 시도

---

src/main/java/sync/slamtalk/chat/service/ChatService.java
src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java

- redisFirstDataBaseLater 에 @Transactional 어노테이션추가

bug : 채팅방 과거 내역 요청 시 메세지 누락 문제 해결 시도

---

src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java

bug : 채팅방 과거 내역 요청 시 메세지 누락 문제 해결 시도(트랜잭션 격리 수준 하향)

---

src/main/java/sync/slamtalk/chat/controller/ChatController.java
src/main/java/sync/slamtalk/chat/dto/Request/ChatPreviousDTO.java
src/main/java/sync/slamtalk/chat/redis/RedisService.java
src/main/java/sync/slamtalk/chat/service/ChatService.java
src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java

- 과거 내역 요청 시 응답 버그 수정 (메세지 저장로직 수정)
- 메세지 요청 횟수 추가, 횟수에 따라 데이터 보내는 갯수 달라지도록

#212 과거 내역 버그 수정, 과거 내역 요청 횟수 추가

---

src/main/java/sync/slamtalk/community/dto/CommunityResponseDTO.java
src/main/java/sync/slamtalk/community/mapper/CommunityMapper.java

#229 유저ID 반환

---

src/main/java/sync/slamtalk/community/controller/CommentController.java
src/main/java/sync/slamtalk/community/controller/CommunityController.java
src/main/java/sync/slamtalk/community/dto/CommunityResponseDTO.java
src/main/java/sync/slamtalk/community/mapper/CommentMapper.java
src/main/java/sync/slamtalk/community/mapper/CommunityMapper.java
src/main/java/sync/slamtalk/community/service/CommunityService.java

#231 게시글 조회 시, 댓글 같이 조회

---

src/main/java/sync/slamtalk/security/config/SecurityConfig.java

- application.yml 파일에도 exception-paths 추가하였습니다
resolved : #231

#231 feat : community 게스트 권한 설정

---

src/main/java/sync/slamtalk/map/controller/AdminBasketballCourtController.java
src/main/java/sync/slamtalk/map/controller/BasketballCourtController.java
src/main/java/sync/slamtalk/map/dto/BasketballCourtAdminRequestDTO.java
src/main/java/sync/slamtalk/map/dto/BasketballCourtFullResponseDTO.java
src/main/java/sync/slamtalk/map/entity/BasketballCourt.java
src/main/java/sync/slamtalk/map/mapper/BasketballCourtMapper.java
src/main/java/sync/slamtalk/map/service/BasketballCourtService.java
src/main/java/sync/slamtalk/map/service/ReportBasketballCourtService.java

- 제보 농구장 수락 시, 채팅방 매핑
- 상세 조회 시, 채팅방 Id 반환

#234 농구장 채팅방 매핑 & 반환

---

src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java
src/main/java/sync/slamtalk/chat/controller/ChatController.java
src/main/java/sync/slamtalk/chat/dto/Request/ChatCreateDTO.java
src/main/java/sync/slamtalk/chat/entity/ChatRoom.java
src/main/java/sync/slamtalk/chat/service/ChatService.java
src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java

- 농구장 채팅방 생성 요청 컨트롤러 추가 
- 농구장 채팅방 생성 메서드 추가
- 필요없는 코드 정리
closed #236

#236 농구장 채팅방 생성

---

src/main/java/sync/slamtalk/community/repository/CommunityRepository.java
src/main/java/sync/slamtalk/mate/repository/MatePostRepository.java
src/main/java/sync/slamtalk/mate/service/MatePostService.java
src/main/java/sync/slamtalk/team/repository/TeamMatchingRepository.java
src/main/java/sync/slamtalk/team/service/TeamMatchingService.java
src/main/java/sync/slamtalk/user/service/UserService.java
src/main/java/sync/slamtalk/user/utils/UserLevelScore.java

- Level 시스템 관련 게시글 작성 조회
- Level 임계값 10으로 설정
- 초기값 레벨 초기화 1로 하기
- CommunityRepository.java
- MatePostRepsitory.java
- TeamMatchingRepsitory.java
- MatePostService.java
- TeamMatchingService.java
수정했습니다 담당자분들 확인 부탁드립니다!
resolved : #232

#232 유저 Level 시스템 관련 게시글 작성 조회 및 Level 임계값 10 으로 설정 및 레벨 초깃값 1로 하기

---

src/main/java/sync/slamtalk/user/service/UserService.java

- 이미지가 null이 들어오거나 아예 없을 경우 업데이트 안되도록 수정
resolved : #250

#250 유저 마이페이지 수정 리팩터링

---

src/main/java/sync/slamtalk/user/service/UserService.java

- .User.getSelfIntroduction()" is null 일 경우 NPE 수정
resolved : #250

#250 bug : user의 값이 null 일때 NPE가 발생하던 오류 수정

---

src/main/java/sync/slamtalk/user/service/UserService.java

#250 유저 마이페이지 수정 

---

src/main/java/sync/slamtalk/user/service/UserService.java

#250 상대방 마이페이지 디버깅용 로직 추가

---

src/main/java/sync/slamtalk/map/dto/BasketballCourtAdminRequestDTO.java
src/main/java/sync/slamtalk/map/dto/BasketballCourtFullResponseDTO.java
src/main/java/sync/slamtalk/map/dto/BasketballCourtReportResponseDTO.java
src/main/java/sync/slamtalk/map/dto/BasketballCourtRequestDTO.java
src/main/java/sync/slamtalk/map/dto/BasketballCourtResponseDTO.java
src/main/java/sync/slamtalk/map/entity/BasketballCourt.java
src/main/java/sync/slamtalk/map/entity/Fee.java
src/main/java/sync/slamtalk/map/entity/NightLighting.java
src/main/java/sync/slamtalk/map/entity/OpeningHours.java
src/main/java/sync/slamtalk/map/entity/ParkingAvailable.java
src/main/java/sync/slamtalk/map/mapper/BasketballCourtMapper.java
src/main/java/sync/slamtalk/map/service/ReportBasketballCourtService.java

- 사용료, 야간조명, 개방시간, 주차 가능 여부 필드 -> enum 수정

#249 사용료, 야간조명, 개방시간, 주차 가능 여부 필드 수정

---

src/main/java/sync/slamtalk/security/jwt/JwtTokenProvider.java
src/main/java/sync/slamtalk/user/service/AuthService.java
src/main/java/sync/slamtalk/user/service/UserService.java

#250 feat : 디버깅용 로직 추가

---

src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java

bug : 리스트 조회 에러 로그 확인

---

src/test/java/sync/slamtalk/user/repository/UserRepositoryTest.java

- UserRepositoryTest 단위 테스트 작성
- @DataJpaTest를 이용해서 Repository 단위 테스트 코드를 작성하였습니다.
- update 쿼리 빼고 모든 쿼리를 검증하였습니다.
resolved : #224

#224 test : UserRepositoryTest

---

src/main/java/sync/slamtalk/mate/repository/QueryRepository.java
src/main/java/sync/slamtalk/team/dto/TeamSearchCondition.java

- TeamMatching 조회 시 searchWord를 통한 추가적인 필터링
>

TeamMatching 조회 시 searchWord를 통한 추가적인 필터링

---

src/main/java/sync/slamtalk/mate/dto/MateSearchCondition.java
src/main/java/sync/slamtalk/mate/repository/QueryRepository.java

feat: MatePost에서 searchWord를 통해 필터링

---

src/main/java/sync/slamtalk/chat/repository/MessagesRepository.java

refactor : 페이징 정렬순서 변경 DESC->ASC

---

src/main/java/sync/slamtalk/chat/controller/ChatController.java
src/main/java/sync/slamtalk/chat/dto/ChatErrorResponseCode.java
src/main/java/sync/slamtalk/chat/redis/RedisService.java
src/main/java/sync/slamtalk/chat/repository/MessagesRepository.java
src/main/java/sync/slamtalk/chat/service/ChatService.java
src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java

Develop -> main merge

---

src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java
src/main/java/sync/slamtalk/chat/repository/MessagesRepository.java
src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java

- 채팅방 입장 후 최신 메세지 조회 안되는 버그 수정

Bug/298 채팅방 입장 후 메세지 버그 수정

---

src/main/java/sync/slamtalk/chat/dto/response/ChatRoomDTO.java
src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java

Feature/301 chat 채팅리스트에서 최신 메세지부터 채팅방 정렬

---

src/main/java/sync/slamtalk/chat/dto/response/ChatRoomDTO.java
src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java

Bug/301 chatList 정렬수정

---

src/main/java/sync/slamtalk/chat/entity/ChatRoom.java
src/main/java/sync/slamtalk/map/controller/AdminBasketballCourtController.java
src/main/java/sync/slamtalk/map/controller/BasketballCourtController.java
src/main/java/sync/slamtalk/map/entity/BasketballCourt.java
src/main/java/sync/slamtalk/map/entity/Fee.java
src/main/java/sync/slamtalk/map/entity/NightLighting.java
src/main/java/sync/slamtalk/map/entity/OpeningHours.java
src/main/java/sync/slamtalk/map/entity/ParkingAvailable.java
src/main/java/sync/slamtalk/map/entity/RegistrationStatus.java
src/main/java/sync/slamtalk/map/mapper/BasketballCourtMapper.java
src/main/java/sync/slamtalk/map/repository/BasketballCourtRepository.java
src/main/java/sync/slamtalk/map/service/AdminBasketballCourtService.java
src/main/java/sync/slamtalk/map/service/BasketballCourtService.java
src/main/java/sync/slamtalk/map/service/ReportBasketballCourtService.java
src/main/java/sync/slamtalk/user/service/UserService.java

- sonarlint 리뷰 참고하여 수정
- 주석 추가 및 메소드명 변경
- 불필요한 애노테이션 삭제
>

#270 농구장 리팩토링

---

src/main/java/sync/slamtalk/common/ErrorResponseCode.java
src/main/java/sync/slamtalk/notification/NotificationController.java
src/main/java/sync/slamtalk/notification/NotificationRepository.java
src/main/java/sync/slamtalk/notification/NotificationSender.java
src/main/java/sync/slamtalk/notification/custom/CustomNotificationRepository.java
src/main/java/sync/slamtalk/notification/custom/CustomNotificationRepositoryImpl.java
src/main/java/sync/slamtalk/notification/dto/request/NotificationRequest.java
src/main/java/sync/slamtalk/notification/dto/response/NotificationResponse.java
src/main/java/sync/slamtalk/notification/model/Notification.java
src/main/java/sync/slamtalk/notification/model/NotificationContent.java
src/main/java/sync/slamtalk/notification/service/InAppNotificationSender.java
src/main/java/sync/slamtalk/notification/service/NotificationService.java
src/main/java/sync/slamtalk/notification/util/StringSlicer.java

feat: In-app 알림 기반 코드 생성

---

src/main/java/sync/slamtalk/map/controller/AdminBasketballCourtController.java
src/main/java/sync/slamtalk/map/service/ReportBasketballCourtService.java

feature : 관리자 거절 기능 구현

---

src/main/java/sync/slamtalk/map/entity/EnumType.java
src/main/java/sync/slamtalk/map/entity/Fee.java
src/main/java/sync/slamtalk/map/entity/NightLighting.java
src/main/java/sync/slamtalk/map/entity/OpeningHours.java
src/main/java/sync/slamtalk/map/entity/ParkingAvailable.java
src/main/java/sync/slamtalk/map/mapper/BasketballCourtMapper.java

- 농구장 조회 시, Enum 타입 그대로 반환되는 값 수정
>

#317 농구장 정보 반환 값 수정

---

src/main/java/sync/slamtalk/chat/redis/RedisService.java
src/main/java/sync/slamtalk/email/EmailController.java
src/main/java/sync/slamtalk/email/EmailErrorResponseCode.java
src/main/java/sync/slamtalk/email/EmailService.java
src/main/java/sync/slamtalk/email/dto/PostMailReq.java
src/main/java/sync/slamtalk/security/config/SecurityConfig.java
src/main/java/sync/slamtalk/security/service/CustomUserDetailsService.java
src/main/java/sync/slamtalk/user/controller/AuthController.java
src/main/java/sync/slamtalk/user/dto/request/UserChangePasswordReq.java
src/main/java/sync/slamtalk/user/dto/request/UserTmpPasswordReq.java
src/main/java/sync/slamtalk/user/error/UserErrorResponseCode.java
src/main/java/sync/slamtalk/user/service/AuthService.java
src/main/java/sync/slamtalk/user/utils/PasswordGenerator.java
src/main/resources/templates/password-reset-template.html

#307 email package 정리하기 

---

src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java
src/main/java/sync/slamtalk/chat/config/StompHandler.java
src/main/java/sync/slamtalk/chat/dto/request/ChatCreateDTO.java
src/main/java/sync/slamtalk/chat/dto/request/ChatMessageDTO.java
src/main/java/sync/slamtalk/chat/dto/response/ChatUserDTO.java
src/main/java/sync/slamtalk/chat/entity/UserChatRoom.java
src/main/java/sync/slamtalk/chat/service/ChatNotificationService.java
src/main/java/sync/slamtalk/chat/service/ChatNotificationServiceImpl.java
src/main/java/sync/slamtalk/chat/service/ChatService.java
src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
src/main/java/sync/slamtalk/chat/service/MessageService.java
src/main/java/sync/slamtalk/notification/NotificationRepository.java
src/main/java/sync/slamtalk/notification/NotificationSender.java
src/main/java/sync/slamtalk/notification/custom/CustomNotificationRepository.java
src/main/java/sync/slamtalk/notification/custom/CustomNotificationRepositoryImpl.java
src/main/java/sync/slamtalk/notification/dto/request/ChatNotificationRequest.java
src/main/java/sync/slamtalk/notification/dto/request/NotificationRequest.java
src/main/java/sync/slamtalk/notification/dto/response/NotificationResponse.java
src/main/java/sync/slamtalk/notification/model/Notification.java
src/main/java/sync/slamtalk/notification/model/NotificationContent.java
src/main/java/sync/slamtalk/notification/model/NotificationType.java
src/main/java/sync/slamtalk/notification/service/InAppNotificationSender.java
src/main/java/sync/slamtalk/notification/service/NotificationService.java

- 알림 코드 수정, 채팅 알림 요구 사항 반영
DB 제약조건 변경이 필요합니다.
`ALTER TABLE notification_content
DROP CONSTRAINT notification_content_chk_1,
ADD CONSTRAINT notification_content_chk_1 CHECK (notification_type BETWEEN 0 AND 10);`

알림 코드 수정, 채팅 알림 요구사항 반영

---

src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java
src/main/java/sync/slamtalk/chat/service/ChatNotificationServiceImpl.java
src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
src/main/java/sync/slamtalk/notification/custom/CustomNotificationRepositoryImpl.java

- 메세지 생성 알림 Uri 추가
- 알림 제거를 채팅 리스트에서 하도록 변경
- ChatNotification query 수정

메세지 생성 알림 내 uri, 알림 삭제 호출 시기 변경 

---

src/main/java/sync/slamtalk/chat/service/ChatNotificationServiceImpl.java

fix : 알림 메세지 수정

---

src/main/java/sync/slamtalk/chat/service/MessageService.java

fix : userName은 무엇인가..userNickName 으로 변경

---

src/main/java/sync/slamtalk/community/dto/CommunityResponseDTO.java
src/main/java/sync/slamtalk/community/mapper/CommunityMapper.java
src/main/java/sync/slamtalk/community/repository/CommentRepository.java
src/main/java/sync/slamtalk/community/service/CommunityService.java

#316 게시글 목록에 댓글 개수 포함

---

src/main/java/sync/slamtalk/user/service/AuthService.java

fix : 임시 비밀번호 발급시 update 쿼리나가게 수정
- @transcational 추가
- password.encoding 추가
resolved #340

#340 임시 비밀번호 발급 api 버그 수정 

---

src/main/java/sync/slamtalk/user/error/UserErrorResponseCode.java
src/main/java/sync/slamtalk/user/service/AuthService.java

develop -> main

---

src/main/java/sync/slamtalk/map/service/ReportBasketballCourtService.java

#343 농구장 알림 기능

---

src/main/java/sync/slamtalk/community/service/CommentService.java

#344 게시글 댓글 알림 기능

---

src/main/java/sync/slamtalk/mate/dto/response/MatePostKeyInformation.java
src/main/java/sync/slamtalk/mate/dto/response/MyMateListRes.java
src/main/java/sync/slamtalk/mate/entity/MatePost.java
src/main/java/sync/slamtalk/mate/service/MatePostService.java
src/main/java/sync/slamtalk/team/controller/TeamMatchingController.java
src/main/java/sync/slamtalk/team/dto/response/MyTeamMatchingListRes.java
src/main/java/sync/slamtalk/team/dto/response/TeamMatchingKeyInformation.java
src/main/java/sync/slamtalk/team/entity/TeamMatching.java
src/main/java/sync/slamtalk/team/service/TeamMatchingService.java

#296 [팀모집/ 상대팀모집] 1차요구사항 반영

---

src/main/java/sync/slamtalk/common/Site.java
src/main/java/sync/slamtalk/mate/event/CompleteMateEvent.java
src/main/java/sync/slamtalk/mate/event/MatePostPostDeletionEvent.java
src/main/java/sync/slamtalk/mate/event/MateSupportAcceptanceEvent.java
src/main/java/sync/slamtalk/mate/event/MateSupportEvent.java
src/main/java/sync/slamtalk/mate/service/MateDeclineEvent.java
src/main/java/sync/slamtalk/mate/service/MatePostService.java
src/main/java/sync/slamtalk/mate/service/ParticipantService.java
src/main/java/sync/slamtalk/notification/listener/mate/CompleteMatePostNotifier.java
src/main/java/sync/slamtalk/notification/listener/mate/MatePostDeleteNotifier.java
src/main/java/sync/slamtalk/notification/listener/mate/MatePostRejectSupportNotifier.java
src/main/java/sync/slamtalk/notification/listener/mate/MatePostSupportAcceptanceNotifier.java
src/main/java/sync/slamtalk/notification/listener/mate/MatePostSupportNotifier.java

- 메이트 지원 시 게시글자에게 알림 생성
- 메이트 지원 수락 시 지원자에게 알림
- 메이트 지원 거절 시 지원자에게 알림
- 메이트 게시글 삭제 시 참여자 전원에게 알림
- 메이트 매칭 완료 시 참여자 전원에게 알림

#296 Mate 관련 알림 요구사항 반영

---

src/main/java/sync/slamtalk/common/Site.java
src/main/java/sync/slamtalk/mate/service/MatePostService.java
src/main/java/sync/slamtalk/notification/listener/team/CompleteTeamMachingNotifier.java
src/main/java/sync/slamtalk/notification/listener/team/TeamMatchingDeleteNotifier.java
src/main/java/sync/slamtalk/notification/listener/team/TeamMatchingRejectSupportNotifier.java
src/main/java/sync/slamtalk/notification/listener/team/TeamMatchingSupportAcceptanceNotifier.java
src/main/java/sync/slamtalk/notification/listener/team/TeamMatchingSupportNotifier.java
src/main/java/sync/slamtalk/notification/model/NotificationType.java
src/main/java/sync/slamtalk/team/event/CompleteTeamMatchingEvent.java
src/main/java/sync/slamtalk/team/event/TeamMatchingPostDeletionEvent.java
src/main/java/sync/slamtalk/team/event/TeamMatchingSupportAcceptanceEvent.java
src/main/java/sync/slamtalk/team/event/TeamMatchingSupportEvent.java
src/main/java/sync/slamtalk/team/event/TeamMatchingSupportRejectionEvent.java
src/main/java/sync/slamtalk/team/service/TeamMatchingService.java

- 팀 매칭 지원 시 게시글자에게 알림 생성
- 팀 매칭 지원 수락 시 지원자에게 알림
- 팀 매칭 지원 거절 시 지원자에게 알림
- 팀 매칭 게시글 삭제 시 참여자 전원에게 알림
- 팀 매칭 매칭 완료 시 참여자 전원에게 알림

#296 팀매칭 알림 요구사항 구현

---

src/main/java/sync/slamtalk/notification/listener/mate/CompleteMatePostNotifier.java
src/main/java/sync/slamtalk/notification/listener/mate/MatePostDeleteNotifier.java
src/main/java/sync/slamtalk/notification/listener/mate/MatePostRejectSupportNotifier.java
src/main/java/sync/slamtalk/notification/listener/mate/MatePostSupportAcceptanceNotifier.java
src/main/java/sync/slamtalk/notification/listener/mate/MatePostSupportNotifier.java
src/main/java/sync/slamtalk/notification/listener/team/CompleteTeamMachingNotifier.java
src/main/java/sync/slamtalk/notification/listener/team/TeamMatchingDeleteNotifier.java
src/main/java/sync/slamtalk/notification/listener/team/TeamMatchingRejectSupportNotifier.java
src/main/java/sync/slamtalk/notification/listener/team/TeamMatchingSupportAcceptanceNotifier.java
src/main/java/sync/slamtalk/notification/listener/team/TeamMatchingSupportNotifier.java

- 따옴표 없애기
- 시간 없애기
- 불필요한 특수문자 없애기
resolved : #296

# [팀매칭/메이트매칭] 알림 메세지 format 바꾸기

---

src/main/java/sync/slamtalk/chat/service/MessageService.java

fix : 알림 url 수정

---

src/main/java/sync/slamtalk/security/jwt/JwtTokenProvider.java
src/main/java/sync/slamtalk/security/oauth2/handler/OAuth2LoginSuccessHandler.java
src/main/java/sync/slamtalk/user/service/AuthService.java

[로그인 버그] 동시접속 가능하게 끔 하는 로직

---

src/main/java/sync/slamtalk/mate/error/MateErrorResponseCode.java
src/main/java/sync/slamtalk/mate/service/MatePostService.java
src/main/java/sync/slamtalk/team/error/TeamErrorResponseCode.java
src/main/java/sync/slamtalk/team/service/TeamMatchingService.java

[팀매칭/상대팀매칭] 게시글 시간 검증 로직 추가

---

src/main/java/sync/slamtalk/security/logout/CustomLogoutHandler.java

로그아웃 시 모든 계정이 로그아웃 되는 경우가 발생되는 버그 수정

로그아웃 시 모든 계정이 로그아웃 되는 경우가 발생되는 버그 수정 

---

src/main/java/sync/slamtalk/map/service/ReportBasketballCourtService.java

농구장 제보 수정 권한 변경
